### ISSUE TITLE
Major Refactoring for 1.0

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#2210]
This will be a master ticket for all things refactoring before 1.0 release.
- [x] Split TileLayer into GridLayer (grid logic) and TileLayer (image tiles logic). PR #2247, ref #1180
- [x] Refactor the layers architecture (have a base class for layers and DRY up everything — event handling, zoom animation logic, zIndex and pane handling, etc.). PR #2266, ref #496 #1742 #1249 
- [x] Refactor projections into Earth-based and others, move all Earth hardcode (wrapping tiles, world copy jump, etc.) to CRS, make it dead easy to use flat maps. PR #2247; ref #2239
- [x] Refactor vector layers so that Canvas and SVG can be used together at the same time and switched in real-time, and groups of features can be handled in batch (e.g. when adding/updating/removing a bunch of features at once) to improve performance. #155 #1662 #1852 #2240
- [ ] Refactor zoom animation logic to make the long-awaited Easey-style animations (zoom-panning between points) possible. #1413
