### ISSUE TITLE
1.0 Documentation checklist

### ISSUE THREAD

**Issue by patrickarlt** [Leaflet/Leaflet#3098]
@mourner I'm going to have some more time over the next 2 weeks (holidays!) to tackle more documentation related tasks and thought I would start by pulling together the various change logs and major issues into a checklist so we can get an idea of what needs to be done to the docs.

I'll work on picking stuff off this list and making PRs into the `gh-pages-master` branch.

#### Vectors refactoring

**Currently in progress in https://github.com/Leaflet/Leaflet/pull/3101**

* [x] Added `Renderer` layer (inherited by SVG/Canvas implementations) that handles renderer bounds and zoom animation.
* [x] ~~Added `SVG` & `Canvas` classes that now contain all renderer-specific code for vector layers and can be added as layers to the map.~~ *Probably not worth documenting at this time*
* [x] All vector layer classes (`Path`, `Polyline`, etc.) now don't contain any renderer-specific code and instead can be passed a renderer layer to use as `renderer` in options;
* [x] Removed `MultiPolyline` and `MultiPolygon` classes since multiple rings are now handled by `Polyline` and `Polygon` classes respectively. Layers with multiple rings now perform much better (since each is now physically a single path object instead of being a `FeatureGroup` of layers).
* [x] ~~Added retina support for Canvas layers.~~ *Doesn't include API changes that need to be documented*
* [x] Improved default vector layer styles.
* [x] Added `Polyline` and `Polygon` `getCenter` for getting centroids.
* [x] Changed `Circle` to inherit from `CircleMarker` and not the other way.

#### Layers refactoring

**Some items in progress in https://github.com/Leaflet/Leaflet/pull/3097** and https://github.com/Leaflet/Leaflet/pull/3107

* [x] Added `Layer` class which all layers added to a map should inherit from.
* [x] Added `add` and `remove` events to all layers.
* [x] Added `remove` method to layers and controls (`marker.remove()` is now equivalent to `map.removeLayer(marker)`).
* [x] Added `pane` option to all layers that can be changed (e.g. you can set `pane: 'overlayPane'` to a tile layer).
* [x] Added `map` `createPane` method for custom panes. [#1742](https://github.com/Leaflet/Leaflet/issues/1742)
* [x] Simplified map panes &mdash; removed `objectsPane`, all panes are on the same level now.
* [x] Added `shadowPane` option to markers as well.
* [x] Added `getEvents` method to all layers that returns an `{event: listener, ...}` hash; layers now manage its listeners automatically without having to do this in `onAdd`/`onRemove`.
* [x] Added `togglePopup`, `setPopupContent`, `getPopup` methods to all layers. [#2279](https://github.com/Leaflet/Leaflet/issues/2279) [#2292](https://github.com/Leaflet/Leaflet/issues/2292)
* [x] ~~Removed `Map` `tilelayersload` event.~~ *This was already removed by someone else*
* [x] Removed `Popup` `open` and `close` events in favor of `add` and `remove` for consistency.

#### GridLayer + TileLayer 

* [x]  split `TileLayer` into `GridLayer` (with all the grid / tile positioning logic) and its child `TileLayer` (with logic for loading image tiles from tile servers)
* [x] remove `TileLayer.Canvas` in favor of a much more flexible and powerful `GridLayer`

#### CRS & Projections

* [x] add `Projection` `bounds` property which determines projected coordinates bounds
* [x] add `CRS` properties: `wrapLng`, `wrapLat` (determining whether the world wraps and how) and `infinite` (if true, the layer will not be bounded, with negative tiles etc.)
* [x] add `CRS` `getProjectedBounds` that returns projected world bounds for zoom and corresponding `Map` `getPixelWorldBounds`, derived from `Projection` `bounds`, used for wrapping/bounding tiles
* [ ] fix `EPSG:4326` to have 2x1 tiles at zoom 0, #1207
* [ ] fix `Projection.SphericalMercator` to project to meter units
* [x] add `CRS` `unproject`
* [x] remove `LatLng` `wrap` and add `CRS` and `Map` `wrapLatLng` that depends on CRS, fix #1618 again

#### TileLayer-related changes

These changes make implementing custom grid-like layers for Leaflet much easier.

* [x] ~~Moved most of the `TileLayer` logic into the new `GridLayer` class (which `TileLayer` now inherits, extending it with logic specific to tile servers).~~ *Internal logic changes don't need to be documented*
* [x] Removed `TileLayer.Canvas` in favor of the much more flexible and powerful `GridLayer`.
* [x] ~~Improved tile wrapping and bounding logic in `TileLayer` to work transparently and completely depent on the CRS used; removed the need for `TileLayer` hacks when using custom projections.~~ *No public API changes*
* [x] ~~Removed `url` property in `tileload` and `tileloadstart` events (get it through `tile.src`).~~ *Removed by someone else*

#### Projections-related changes

* [x] Added `CRS.Earth` which serves as a base for all Earth-based CRS (`EPSG3857` etc.). [#2345](https://github.com/Leaflet/Leaflet/pull/2345)
* [x] Added `Projection` `bounds` property that defines bounds for different projections (`Mercator`, etc.) in projected coordinates (by [@perliedman](https://github.com/perliedman)).
* [x] Added `CRS` `wrapLat` and `wrapLng` properties which define whether the world wraps on a given axis and in what range. Set as `[-180, 180]` for `EPSG:3857`, `EPSG:4326`, `EPSG:3395` by default.
* [x] Added `CRS` and `Map` `wrapLatLng` (the latter depends on the chosen CRS).
* [x] Added `CRS` `infinite` property that disables boundaries (the world can go on infinitely in any direction), default for `CRS.Simple`.
* [x] Added `CRS` `getProjectedBounds` and `Map` `getPixelWorldBounds` methods that returns world bounds in projected coordinates depending on zoom (derived from `Projection` `bounds`) (by [@perliedman](https://github.com/perliedman)).
* [x] Added `CRS` `unproject` method that converts coordinates in CRS-dependent units into `LatLng` coordinates (by [@sowelie](https://github.com/sowelie)).
* [x] Added `Map` `distance(latlng1, latlng2)` method that takes CRS into account and works with flat projections.  [#2345](https://github.com/Leaflet/Leaflet/pull/2345) [#1442](https://github.com/Leaflet/Leaflet/issues/1442)
* [x] ~~Improved `Circle` to be approximated with an ellipse in Earth-based projections. [#2345](https://github.com/Leaflet/Leaflet/pull/2345)~~ *not something that really needs documentation*

### Other breaking API changes

* [x] Changed `DomUtil` `off` to require `context` attribute if you remove a listener that was previously added with a particular context.
* [x] Removed `DomUtil.getViewportOffset` method as it is no longer necessary.
* [x] Removed `DomUtil` `getTranslateString` and `getScaleString` methods.
* [x] Removed `DomUtil` `documentIsLtr` method.
* [x] Removed `LatLng` `RAD_TO_DEG`, `DEG_TO_RAD` and `MAX_MARGIN` constants.
* [x] Renamed `Util.limitExecByInterval` to `Util.throttle`.

### Other API improvements

* [x] Added `Evented` class that now many Leaflet classes inherit from (instead of mixing in events methods in each class), while keeping the old `includes: L.Mixin.Events` syntax available. [#2310](https://github.com/Leaflet/Leaflet/pull/2310)
* [x] ~~Improved `Class` `options` to be prototypically inherited instead of copied over in children classes, which leads to more efficient memory use, faster object construction times and ability to change parent options that get propagated to all children automatically (by [@jfirebaugh](https://github.com/jfirebaugh)). [#2300](https://github.com/Leaflet/Leaflet/pull/2300) [#2294](https://github.com/Leaflet/Leaflet/issues/2294)~~ *I don't think this is actually a change that needs to be documented since its internal only*
* [x] Added `{r}` variable to `TileLayer` `url` for adding `"@2x"` prefix on Retina-enabled devices (by [@urbaniak](https://github.com/urbaniak)). [#2296](https://github.com/Leaflet/Leaflet/pull/2296)
* [x] Added `Point` `ceil` method (by [@perliedman](https://github.com/perliedman)).
* [x] Added `Util.wrapNum` method for wrapping a number to lie in a certain range.
* [x] Improved `L.bind` to use native `Function` `bind` on modern browsers and prepend real arguments to bound ones.
* [x] Added `LatLng` `equals` second argument `maxMargin`.
* [x] Added `DomUtil` `setClass` and `getClass` methods.
* [x] Improve `Marker` `move` event to include `oldLatlng` (by [@danzel](https://github.com/danzel)). [#2412](https://github.com/Leaflet/Leaflet/pull/2412)
* [x] Improved `DomEvent` `on`/`off` to accept space-separated events and object literals (`{type: fn}`).
* [ ] Added `DomUtil` `toFront` and `toBack` methods.
* [x] Added `Evented` `listens` as a shortcut to `hasEventListeners`.
* [x] Added optional support for center-oriented scroll for `L.map` option `touchZoom` (by [@mtmail](https://github.com/mtmail)). [#2527](https://github.com/Leaflet/Leaflet/pull/2527)

**Comment by mourner** [comment]
OK back to work tomorrow after today's Christmas!

**Comment by mourner** [comment]
Merged all the PRs and did an epic rebase of `gh-pages-master` on top of `gh-pages`, hope nothing got lost or broke...

**Comment by mourner** [comment]
Now I want to have an attempt at #3277

**Comment by patrickarlt** [comment]
* [ ] Update renderer and pane docs based on https://github.com/Leaflet/Leaflet/pull/3266
* [ ] Remove duplicate methods now that #3107 and #3097 are merged

**Comment by perliedman** [comment]
I've begun documenting the changes to CRS and projection over in the `docs-projection` branch: https://github.com/Leaflet/Leaflet/tree/docs-projection

I'm done with the first section listed above, "CRS & Projections". I'll go through "Projections-related changes" next.

**Comment by mourner** [comment]
@perliedman awesome, thanks a lot for taking care of this!

**Comment by mourner** [comment]
Looks like we covered pretty much everything here. Lets track remaining stuff as separate issues.
