### ISSUE TITLE
Release Tracker - v1.9.3

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8634]
Some merged PRs should be cherry picked to the `v1`:

- [ ] #7344
- [ ] #8562
- [ ] #8571
- [ ] #8556
- [ ] #8550
- [ ] #8548
- [ ] #8547
- [ ] #8520
- [ ] #8534

I hope that are all

**Comment by Falke-Design** [comment]
@jonkoops can you do the cherry pick?

**Comment by jonkoops** [comment]
Done, @Falke-Design could you double check my work to ensure it's all there?

**Comment by jonkoops** [comment]
Perhaps we also want to try and get #8613 in?

**Comment by Falke-Design** [comment]
> Done, @Falke-Design could you double check my work to ensure it's all there?

everything looks good 👍 

> Perhaps we also want to try and get https://github.com/Leaflet/Leaflet/pull/8613 in?

I prefer to do not. I'm currently not able to say if this changes are ok. Code in `GridLayer.js` is changed so it can cause bigger issues 😕 On the other hand, I think this is our last release in `v1` because now we have modernized the code to much for cherry picks.

**Comment by jonkoops** [comment]
Awesome, thanks for checking. Then I think we should compile some release notes and start a release. I'll see if I have some time in the coming days.

**Comment by Falke-Design** [comment]
@jonkoops I prepared the Release Changelog: https://github.com/Leaflet/Leaflet/releases/tag/untagged-cdf564bc2cadf55978e8

The messages need to be refactored

**Comment by Malvoz** [comment]
@Falke-Design I made a small edit to the draft (to include more headings other than Bugs, etc.), and had to edit your link above as the URL returned a 404 after my edit.

**Comment by jonkoops** [comment]
Thanks for compiling that list @Falke-Design! I've done another pass on the release notes. Could y'all take another look and let me know if things look good to you?

cc @Malvoz @mourner

**Comment by Malvoz** [comment]
@jonkoops Link please 🙂

**Comment by Malvoz** [comment]
@jonkoops Yes, https://github.com/Leaflet/Leaflet/releases/tag/untagged-2b81fc8a1a85a12e1352 LGTM. Again, the URL for the drafts changes with each edit...

**Comment by jonkoops** [comment]
Awesome, thanks for checking. I'll get started on the release as soon as the others agree to the contents 👍

**Comment by Falke-Design** [comment]
@jonkoops looks good! 👍

**Comment by mourner** [comment]
@jonkoops looks good to me! Only nit: supporting `position: sticky` seems like more of a bug fix rather than a feature.

**Comment by Malvoz** [comment]
@mourner I added that, moved to Bug fixes in https://github.com/Leaflet/Leaflet/releases/tag/untagged-decdba6297c17613cb25.

**Comment by Falke-Design** [comment]
@jonkoops can I help in someway for the release?

**Comment by jonkoops** [comment]
I'm currently attending a conference in the US, I'll be back in action next week. But if anyone feels like taking this release I'd say go for it.

It's important that we can all do the release so that we don't get blocked on a single point.

**Comment by Falke-Design** [comment]
Maybe I have enough time tomorrow. Then I will try it

**Comment by plarner30** [comment]
@jonkoops hey any chance this could be released soon?

**Comment by Falke-Design** [comment]
## Releasing a new version of Leaflet

- [ ] Ensure all https://github.com/Leaflet/Leaflet/labels/blocker issues and pull requests are resolved.
- [ ] Update [the changelog](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md) since last release and commit.
- [ ] Run `npm version <patch | minor | major>` (this will bump the version in `package.json` and create a new tag).
- [ ] Run `git push --follow-tags` to push the commit created by NPM to Github (together with the tag).
- [ ] Wait for the CI to complete and follow the logs to make sure it runs successfully.
- [ ] Verify that the release was correctly published to NPM by checking:
  - [ ] [Leaflet NPM package page](https://www.npmjs.com/package/leaflet)
  - [ ] files on [Leaflet unpkg page](https://unpkg.com/leaflet@latest/)
- [ ] Make a new release on [Leaflet's GitHub release page](https://github.com/Leaflet/Leaflet/releases/) with the most important parts of the changelog
- [ ] Download zip archive from https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/vX.X.X/leaflet.zip (where `X.X.X` is the new version number) and upload it as an "asset" of the GitHub release.

### Updating docs after the release

- [ ] Make a new branch for the update
- [ ] Write a blog post about the new release and put it in `/docs/_posts/`
- [ ] [Click here to save a snapshot](https://web.archive.org/save/https://leafletjs.com/reference.html)
of the version of docs prior to this release to the Internet Archive's Wayback Machine
(and optionally, add a link to the snapshot in `docs/reference-versions.html`).
- [ ] Run `npm run docs` to generate the new `docs/reference.html` and update integrity hashes in `docs/_config.yml`
- [ ] Update link to latest release in `docs/download.md`
- [ ] Update the announcement section in `docs/index.html`
- [ ] Commit all the changes and submit a PR for someone to review

**Comment by Falke-Design** [comment]
@mourner @jonkoops I think I have not enough rights to do the release.

**Comment by mourner** [comment]
@Falke-Design which ones are you lacking specifically? Let me fix this...

**Comment by Falke-Design** [comment]
@mourner I can't push directly to `v1`, so I can't create the version bump / creating the tag:

![grafik](https://user-images.githubusercontent.com/19800037/202767479-ac356aaa-a39c-49e3-9f4c-caa1a6015108.png)

**Comment by Falke-Design** [comment]
@mourner I see that the tag was created, but the package.json not pushed to the repo. Did this now caused a problem with npm? 😶

https://github.com/Leaflet/Leaflet/tags

**Comment by mourner** [comment]
It seems to have worked: https://github.com/Leaflet/Leaflet/actions/runs/3499008308/jobs/5860105784
I'm in a blackout right now but will figure out the proper way to handle v1 push thing later, but can you try again now?

**Comment by Falke-Design** [comment]
I pushed it again. Worked now 👍 
It looks like everything works and is right. `L.version` in npm is `1.9.3` and the `package.json` in the [tag source code](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.3) also contains `1.9.3`

**Comment by Falke-Design** [comment]
Release is done 🎉

**Comment by jonkoops** [comment]
Very nice, thanks for taking this one @Falke-Design!
